export const electronFlags = [
  ["--auth-server-whitelist", "<url>"],
  ["--auth-negotiate-delegate-whitelist", "<url>"],
  ["--disable-ntlm-v2"],
  ["--disable-http-cache"],
  ["--disable-http2"],
  ["--disable-renderer-backgrounding"],
  ["--disk-cache-size", "<size>"],
  ["--enable-logging", "[file...]"],
  ["--force-fieldtrials", "<trials>"],
  ["--host-rules", "<rules>"],
  ["--host-resolver-rules", "<rules>"],
  ["--ignore-certificate-errors"],
  ["--ignore-connections-limit", "<domains>"],
  ["--js-flag", "<flags>"],
  ["--lang", "<lang>"],
  ["--log-file", "<path>"],
  ["--log-net-log", "<path>"],
  ["--log-level", "<N>"],
  ["--no-proxy-server"],
  ["--no-sandbox"],
  ["--proxy-bypass-list", "<hosts>"],
  ["--proxy-pac-url", "<url>"],
  ["--proxy-server", "<address:port>"],
  ["--remote-debugging-port", "<port>"],
  ["--v", "<log_level>"],
  ["--vmodule", "<pattern>"],
  ["--force_high_performance_gpu"],
  ["--force_low_power_gpu"],
  ["--inspect-brk", "[host:port...]"],
  ["--inspect-port", "<host:port>"],
  ["--inspect", "<host:port...>"],
  ["--inspect-publish-uid", "<stderr,http>"],
];
